version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

  webapi:
    build:
        context: ../../..
        dockerfile: ./examples/NewRelic.OpenTelemetry/MicroserviceExample/WebApi/Dockerfile
    image: opentelemetry-example-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - NEWRELIC_APIKEY=${NEWRELIC_APIKEY}
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq

  workerservice:
    build: 
        context: ../../..
        dockerfile: ./examples/NewRelic.OpenTelemetry/MicroserviceExample/WorkerService/Dockerfile
    image: opentelemetry-example-workerservice
    environment:
      - DOTNET_ENVIRONMENT=Development
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - NEWRELIC_APIKEY=${NEWRELIC_APIKEY}
    restart: on-failure
    depends_on:
      - rabbitmq
